module.exports = {
  'Tennis': [
    'Miami - N.Milojevic v H.Hurkacz',
    'Miami - L.Vanni v A.Karatsev',
    'Miami - Y.Bai/Rigele Te v C-P.Hsieh',
    'Miami - J.Monaco v F.Delbonis',
    'Miami - C.Ruud v YH.Lu',
    'Miami - N.Basilashvili v T.Robredo',
    'Miami - D.Istomin v A.Kuznetsov',
    'Miami - M.Klizan v B.Paire',
    'Miami - M.Granollers v B.Coric',
    'Miami - A.Rublev v F.Mayer',
    'Miami - T.Bellucci v S.Robert',
    'Miami - A.Dolgopolov v M.Jaziri',
    'Miami - A.Pavlasek v T.Harry-Fritz',
    'Miami - Y-Y.Duan v L.Siegemund',
    'Miami - M.Minella v Kr.Pliskova'
  ],
  'Cricket': [
    'ODI - Afghanistan v Ireland',
    'Test - New Zealand v South Africa',
    'Test - India v Australia 4th Test',
    'ODI - Australia v New Zealand',
    'ODI - Pakistan v England',
    'ODI - Australia v New Zealand',
    'ODI - Pakistan v England',
    'ODI - Pakistan v New Zealand',
    'ODI - Australia v England',
    'ODI - India v New Zealand',
    'ODI - Australia v India'
  ],
  'Horse Racing': [
    '11:05 Turffotien',
    '11:40 Turffotien',
    '12:30 Turffotien',
    '01:30 Turffotien',
    '02:30 Turffotien',
    '03:30 Turffotien',
    '11:30 Chantilly',
    '02:00 Chantilly',
    '03:00 Chantilly',
    '04:05 Chantilly',
    '10:30 Chantilly',
    '11:05 Exeter',
    '11:40 Exeter',
    '12:30 Exeter',
    '01:30 Exeter',
    '02:30 Exeter',
    '03:30 Exeter',
    '11:30 Wetherby',
    '02:00 Wetherby',
    '03:00 Wetherby',
    '04:05 Wetherby',
    '10:30 Wetherby'
  ],
  'Football': [
    'IF - Indonesia v Myanmar',
    'League One - Rochdale v Millwall',
    'League One - Oxford Utd v Bolton',
    'League One - Coventry v Port Vale',
    'League Two - Newport v Luton',
    'League Two - Morecambe v Accrington',
    'National League - Torquay v Eastleigh',
    'National League - Braintree v Woking',
    'National League - Barrow v Wrexham',
    'National League - Aldershot v Dag And Red',
    'National League - Boreham Wood v Lincoln',
    'National League - Gateshead v Guiseley',
    'Premier League - Liverpool v Everton',
    'Premier League - Chelsea v Crystal Palace',
    'Premier League - Man Utd v West Brom',
    'Premier League - Burnley v Tottenham',
    'Premier League - Leicester v Stoke',
    'Premier League - Watford v Sunderland',
    'Premier League - Hull v West Ham',
    'Premier League - Southampton v Bournemouth',
    'Premier League - Swansea v Middlesbrough',
    'Premier League - Arsenal v Man City'
  ]
}
